
services:

  sngrep:
    build:
      context: ./sngrep
      dockerfile: Dockerfile
    container_name: sngrep
    privileged: true  
    network_mode: host 
    environment:
      - TERM=xterm
    cap_add:
      - NET_ADMIN

  db:
    image: mysql:5.7
    # restart: always
    container_name: db01
    environment:
      MYSQL_DATABASE: ${KAM_DB_NAME} # does not matter - will be overriden by kamdbctl on reinit
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'ro_password'
      MYSQL_ROOT_PASSWORD: 'rw_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      internal:
        ipv4_address: ${DB_INTERNAL_IP}

  rtpengine-edge:
    build:
      context: ./rtpengine-edge/docker
      dockerfile: Dockerfile
    container_name: rtpengine-edge
    ports:
      - "23000-23100:23000-23100"
    volumes:
      - ./rtpengine-edge/config:/etc/rtpengine
    depends_on:
      - db
    networks:
      external:
        ipv4_address: 192.168.254.3
      internal:
        ipv4_address: 172.16.254.3

  kamailio-edge:
    image: kamailio/kamailio-ci:5.4-alpine.debug
    container_name: kamailio-edge
    ports:
      - "5090:5060"
    volumes:
      - ./kamailio-default/:/etc/kamailio
      - ./.env:/etc/env
    environment:
      - KAM_SHM_MEM_SIZE=256
      - PUBLIC_SUBNET=${PUBLIC_SUBNET}
      - PUBLIC_IP=${KAM_PUBLIC_IP}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}
      - INTERNAL_IP=${KAM_INTERNAL_IP}
      - UDP_PORT=${KAM_UDP_PORT}
      - TLS_PORT=${KAM_TLS_PORT}
      - DBHOST=${DB_INTERNAL_IP}
      - DBNAME=${KAM_DB_NAME}
      - DBUSER=${KAM_DB_RW_USER}
      - DBPASS=${KAM_DB_RW_PASS}
    depends_on:
      - db
    networks:
      external:
        ipv4_address: ${KAM_PUBLIC_IP}
      internal:
        ipv4_address: ${KAM_INTERNAL_IP}

  b2bua_internal_01:
    tty: true
    container_name: b2bua_internal_01 
    stdin_open: true
    image: andrius/pjsua:latest
    command: pjsua --config-file=/config/pjsua.cfg
    volumes:
      - ./b2bua/internal_01:/config
    ports:
      - "5091:5060"
    networks:
      internal:
        ipv4_address: 172.16.254.100

  b2bua_internal_02:
    tty: true
    container_name: b2bua_internal_02 
    stdin_open: true
    image: andrius/pjsua:latest
    command: pjsua --null-audio --no-tcp --auto-answer=200 --id sip:int2@sip3.archertech.ru
    ports:
      - "5092:5060"
    networks:
      internal:
        ipv4_address: 172.16.254.101

  b2bua_external_01:
    tty: true
    container_name: b2bua_external_01
    stdin_open: true
    image: andrius/pjsua:latest
    command: pjsua --config-file=/config/pjsua.cfg
    volumes:
      - ./b2bua/external_01:/config
    ports:
      - "5093:5060"
    networks:
      external:
        ipv4_address: 192.168.254.100

  b2bua_external_02:
    tty: true
    container_name: b2bua_external_02
    stdin_open: true
    image: andrius/pjsua:latest
    command: pjsua --null-audio --no-tcp --auto-answer=200
    networks:
      external:
        ipv4_address: 192.168.254.101

networks:
    external:
        # use the bridge driver, but enable IPv6
        ipam:
            config:
                - subnet: 192.168.254.0/24
                  gateway: 192.168.254.1
    internal:
        # use a custom driver, with no options
        ipam:
            config:
                - subnet: 172.16.254.0/24
                  gateway: 172.16.254.1
